### ISSUE TITLE
Numix broken on ubuntu 16.04

### ISSUE THREAD

**Issue by startas** [numixproject/numix-gtk-theme#305] opened 2016-04-04 10:41 UTC
Numix is totaly broken on ubuntu 16.04 - window borders doesn't work, icons theme doesn't work, works only elements inside window - buttons and so on.

**Comment by khurshid-alam** [comment] 2016-04-05 15:46
@startas Did you install it from PPA?

**Comment by startas** [comment] 2016-04-07 14:22
Yes.

**Comment by khurshid-alam** [comment] 2016-04-07 14:30
@startas Screenshot? Also make sure that you have `gtk2-engines-murrine` installed.

**Comment by startas** [comment] 2016-04-10 10:57
[Screenshot](http://s30.postimg.org/vmwqj7qkh/Screenshot.png) as you can see, window borders and unity top bar is from default theme and only inside window elements are using numix theme. Also, nautilus files browser is not using numix theme at all, all dependencies installed.

**Comment by khurshid-alam** [comment] 2016-04-11 07:23
Under install and use `gnome-tweak-tool` and change the theme with that. Or try changing window manger theme with dconf editor or try running this command `gsettings set org.gnome.desktop.wm.preferences theme Numix`

**Comment by Argus768** [comment] 2016-04-23 14:33
When i install the numix - circle theme on ubuntu 16.04 i had a lot of problems... First the theme looks ok but when i restart my pc the theme looks broken, the windows are setting on defult and the icons dont work on luncher... How can i fix this?

**Comment by mlms13** [comment] 2016-04-23 14:50
Same issue here on Ubuntu 16.04. Initially it worked fine, but after restarting my computer, no amount of switching between themes will get Numix (gtk or icons) to work correctly. I even tried reinstalling `numix-icon-theme` and `numix-gtk-theme`, but no luck.

Unity Tweak Tool, Gnome Tweak Tool, and `gsettings` all tell me that my icon theme is `Numix-circle` and my gtk theme is `Numix`, but I'm stuck with default icons and window borders.

**Comment by khurshid-alam** [comment] 2016-04-23 15:02
What is the output of `ls -l /usr/share/themes | grep "Numix"` ?

**Comment by Argus768** [comment] 2016-04-23 15:11
lrwxrwxrwx  1 root root   29 Απρ  23 18:08 Numix -> /usr/share/themes/Numix Daily
drwxr-xr-x 11 root root 4096 Απρ  23 18:08 Numix Daily

**Comment by Argus768** [comment] 2016-04-23 15:14
Screenshots: 1) https://postimg.org/image/9wodcc0ef/ 2) https://postimg.org/image/3x57mf4zr/

I have exactly the same problem with mlms13...

**Comment by mlms13** [comment] 2016-04-23 15:28
`ls -l` gives me the same output as Argus768 :

```
lrwxrwxrwx  1 root root   29 Apr 22 22:24 Numix -> /usr/share/themes/Numix Daily
drwxr-xr-x 11 root root 4096 Apr 23 08:39 Numix Daily
```

**Comment by khurshid-alam** [comment] 2016-04-23 15:36
And the output of `ls -l /usr/share/themes/Numix` ?

**Comment by Argus768** [comment] 2016-04-23 15:39
lrwxrwxrwx 1 root root 29 Απρ  23 18:08 /usr/share/themes/Numix -> /usr/share/themes/Numix Daily

**Comment by khurshid-alam** [comment] 2016-04-23 15:40
Ah sorry , I mean `ls -l "/usr/share/themes/Numix Daily"` ?

**Comment by mlms13** [comment] 2016-04-23 15:42
```
total 88
-rwxr-xr-x 1 root root   160 Apr 22 22:16 CREDITS
drwxr-xr-x 4 root root  4096 Apr 23 08:39 debian
drwxr-xr-x 2 root root  4096 Apr 23 08:39 gtk-2.0
drwxr-xr-x 5 root root  4096 Apr 23 08:39 gtk-3.0
drwxr-xr-x 4 root root  4096 Apr 23 08:39 gtk-3.20
-rwxr-xr-x 1 root root   187 Apr 22 22:16 index.theme
-rwxr-xr-x 1 root root 35147 Apr 22 22:16 LICENSE
-rwxr-xr-x 1 root root  1147 Apr 22 22:16 Makefile
drwxr-xr-x 2 root root  4096 Apr 23 08:39 metacity-1
drwxr-xr-x 2 root root  4096 Apr 23 08:39 openbox-3
-rwxr-xr-x 1 root root  1775 Apr 22 22:16 README.md
drwxr-xr-x 3 root root  4096 Apr 23 08:39 unity
drwxr-xr-x 2 root root  4096 Apr 23 08:39 xfce-notify-4.0
drwxr-xr-x 2 root root  4096 Apr 23 08:39 xfwm4
```

**Comment by Argus768** [comment] 2016-04-23 15:46
$ ls -l /usr/share/themes/Numix Daily
ls: cannot access 'Daily': No such file or directory
lrwxrwxrwx 1 root root 29 Απρ  23 18:08 /usr/share/themes/Numix -> /usr/share/themes/Numix Daily

Hmm...

**Comment by khurshid-alam** [comment] 2016-04-23 15:54
@Argus768 See the double colon. 

@mlms13 It looks ok. For some reason it is not picking up metacity decoration. However I could not reproduce this on my machine (fresh install of 16.04):

![sreencast](http://i.imgur.com/NfesxGC.gif)

**Comment by mlms13** [comment] 2016-04-23 15:56
@khurshid-alam even after a restart? Everything was fine on my fresh install last night until I restarted this morning.

@Argus768 you may have to escape the space in that command for it to run correctly: `ls -l /usr/share/themes/Numix\ Daily` (note the `\` after `Numix`).

**Comment by Argus768** [comment] 2016-04-23 16:00
Oh yea! U have right mlms13... So:

ls -l /usr/share/themes/Numix\ Daily
total 88
-rwxr-xr-x 1 root root   160 Απρ  23 07:16 CREDITS
drwxr-xr-x 4 root root  4096 Απρ  23 18:08 debian
drwxr-xr-x 2 root root  4096 Απρ  23 18:08 gtk-2.0
drwxr-xr-x 5 root root  4096 Απρ  23 18:08 gtk-3.0
drwxr-xr-x 4 root root  4096 Απρ  23 18:08 gtk-3.20
-rwxr-xr-x 1 root root   187 Απρ  23 07:16 index.theme
-rwxr-xr-x 1 root root 35147 Απρ  23 07:16 LICENSE
-rwxr-xr-x 1 root root  1147 Απρ  23 07:16 Makefile
drwxr-xr-x 2 root root  4096 Απρ  23 18:08 metacity-1
drwxr-xr-x 2 root root  4096 Απρ  23 18:08 openbox-3
-rwxr-xr-x 1 root root  1775 Απρ  23 07:16 README.md
drwxr-xr-x 3 root root  4096 Απρ  23 18:08 unity
drwxr-xr-x 2 root root  4096 Απρ  23 18:08 xfce-notify-4.0
drwxr-xr-x 2 root root  4096 Απρ  23 18:08 xfwm4
- @khurshid-alam When i try to change theme or icons (like the gif u send) nothing happnes! The windows remain same... I try to install again the ubuntu 16.04 only for fix this but nothing, also i try to reinstall numix theme but nothing again... After restart all gone wrong...

**Comment by khurshid-alam** [comment] 2016-04-23 16:09
@mlms13 Yes. Even after a restart. Why would a restart change anything? As you can see Numix Daily is owned by root...

Also make sure `metacity-theme-2.xml` and `metacity-theme-3.xml` exist under `Numix Daily/metacity-1` folder and they are not empty.

**Comment by Argus768** [comment] 2016-04-23 16:19
I think its ok... Screenshot: https://postimg.org/image/obpki5tc7/

**Comment by mlms13** [comment] 2016-04-23 16:21
I'm not sure why restarting the computer would make a difference. Initially I thought I was hitting [this issue](http://askubuntu.com/questions/21305/desktop-forgets-theme/43043#43043), but it's an old one that has been [expired on Launchpad](https://bugs.launchpad.net/ubuntu/+source/gnome-settings-daemon/+bug/649809) (and indeed, `gnome-settings-daemon` doesn't even seem to exist in `autostart` anymore) .

But I did find [this question on AskUbuntu](http://askubuntu.com/questions/586106/ubuntu-14-04lts-icons-and-theme-not-working) that suggests running `compiz --replace`, which fixes everything. I'm not exactly sure why, and it seems nasty to run this command every time the computer starts, but at least it's kind of a workaround.

**Comment by khurshid-alam** [comment] 2016-04-23 16:26
Unity uses `unity-settings-daemon`. If you also have `gnome-settings-daemon` installed, then removed it and see if that fixes the issue. You may try open a new bug on launchpad.

For now, I am closing as it is not really a theme issue.

**Closed as completed by khurshid-alam** 2016-04-23 16:26 UTC
Labels: invalid

**Comment by Sispheor** [comment] 2016-07-29 15:59
Hi! Same for me, after the upgrade from 14.04 to 16.04. The theme has been applied, exept for the windows border.
Here a [screenshot](https://postimg.org/image/9ssyhun4n/)
I tried to run compiz --replace everything mentioned in that thread. No changes.
I also tried to uninstall Numix and reinstall.

```
ls -l /usr/share/themes/Numix\ Daily
total 44
-rwxr-xr-x 1 root root  160 Jul 27 21:54 CREDITS
drwxr-xr-x 2 root root 4096 Jul 29 17:44 gtk-2.0
drwxr-xr-x 5 root root 4096 Jul 29 17:44 gtk-3.0
drwxr-xr-x 2 root root 4096 Jul 29 17:44 gtk-3.20
-rwxr-xr-x 1 root root  187 Jul 27 21:54 index.theme
drwxr-xr-x 2 root root 4096 Jul 29 17:44 metacity-1
drwxr-xr-x 2 root root 4096 Jul 29 17:44 openbox-3
-rwxr-xr-x 1 root root 2471 Jul 27 21:54 README.md
drwxr-xr-x 3 root root 4096 Jul 29 17:44 unity
drwxr-xr-x 2 root root 4096 Jul 29 17:44 xfce-notify-4.0
drwxr-xr-x 2 root root 4096 Jul 29 17:44 xfwm4
```

**Comment by khurshid-alam** [comment] 2016-07-29 16:04
It has 1px window border. It can not be increased as it produces other bugs for some window managers.

**Comment by Sispheor** [comment] 2016-07-30 12:41
What I mean is that the top bar looks like Ambiance GTK theme and not numix.

**Comment by khurshid-alam** [comment] 2016-07-30 14:34
That because metacity theme doesn't change when you change theme through tweak-tool (Gnome removed that feature). You can manually set metacity theme from dconf-editor.

**Comment by Sispheor** [comment] 2016-08-01 08:03
I tried

```
gsettings set org.gnome.metacity theme numix
```

But still not working :(

**Comment by Sispheor** [comment] 2016-08-01 08:08
It works! Missing upercase. Thx all!

`gsettings set org.gnome.metacity theme Numix`
