### ISSUE TITLE
LibreOffice menu bar text is completely invisible

### ISSUE THREAD

**Issue by imran27** [numixproject/numix-gtk-theme#397] opened 2016-04-26 10:23 UTC
The texts of the menu options on the menu bar in LibreOffice is completely invisible. They appear when I click them but normally they remain invisible as if nothing is there. When I start it through the terminal it gives out errors related to GTK Theme, see the attached files.
[libreoffice-theme-error.txt](https://github.com/numixproject/numix-gtk-theme/files/236365/libreoffice-theme-error.txt)
![screen_2016-04-26-15 52 51](https://cloud.githubusercontent.com/assets/6375554/14815087/f647936a-0bc6-11e6-9cb2-9154b80ca817.png)

**Comment by SammysHP** [comment] 2016-05-01 17:34
That sounds like an issue with LibreOffice.

I use `SAL_USE_VCLPLUGIN=gtk` which uses the gtk2 implementation instead of `gtk3` for gtk3, but has some glitches. There is also a Qt version with `kde4` but that is buggy as well. You can try `gen` which will use its own toolkit. It works, but is ugly as hell.

**Comment by khurshid-alam** [comment] 2016-05-19 06:33
Distro? GTK Version?

**Comment by imranmunshi** [comment] 2016-05-24 14:19
Arch Linux with gtk 3.20.6-1

**Comment by SammysHP** [comment] 2016-05-24 16:28
The gtk3 implementation of LibreOffice uses a single `widget`. That means that it takes a wrong color for the menu (which is dark gray in Numix). Probably nothing which can be fixed in Numix.

**Comment by imranmunshi** [comment] 2016-05-25 12:31
With the Arc Theme it works fine. But you're right, on Numix it may not work at all!

**Comment by fitojb** [comment] 2016-06-24 23:44
Can you test again with LibreOffice 5.2?

**Comment by SammysHP** [comment] 2016-08-05 09:09
@fitojb 
Yes, with LO 5.2 everything is ok! This issue can be closed.

**Closed as completed** 2016-08-06 17:25 UTC

**Comment by rubin55** [comment] 2016-12-02 07:23
Actually, it's not ok with 5.2; just reproduced this with LibreOffice 5.2.3.3 and Numix 2.6.6 on Gentoo
![2016-12-02-082253_1280x800_scrot](https://cloud.githubusercontent.com/assets/6214491/20826058/a710ebc6-b868-11e6-95ca-9cd9806bd340.png)

**Comment by khurshid-alam** [comment] 2016-12-03 13:53
I couldn't reproduce it either on Ubuntu or on Arch. Can anyone confirm?

**Comment by JPFrancoia** [comment] 2016-12-03 14:03
I'm on Archlinux, libreoffice-fresh 5.2.3-1, numix-themes 2.6.5-1, numix-themes-archblue-git 2.6.4.r2.5a0ec95-2 and I don't have this problem anymore.
