### ISSUE TITLE
Awful black Libre Office separators

### ISSUE THREAD

**Issue by Corsseir** [numixproject/numix-gtk-theme#210] opened 2015-04-24 12:14 UTC
Separators in Libre Office look awful with Numix theme:
https://www.dropbox.com/s/m2crz0bzkyqneue/Screenshot%20from%202015-04-24%2013%3A57%3A55.png?dl=0
https://www.dropbox.com/s/gqmtt98yz1c5j6e/Screenshot%20from%202015-04-24%2014%3A11%3A44.png?dl=0

**Comment by dirtydancing** [comment] 2015-04-26 08:38
I believe this is a duplicate of https://github.com/shimmerproject/Numix/issues/199 and thus this issue can be closed :)

**Comment by megax** [comment] 2016-04-24 12:54
@khurshid-alam Duplicated issue.

**Comment by megax** [comment] 2016-08-22 19:47
@khurshid-alam Closed issue... :) Does not contain additional information.

**Closed as completed** 2016-08-22 20:47 UTC
Labels: duplicate
