### ISSUE TITLE
No check marks in Ubuntu Wily.

### ISSUE THREAD

**Issue by StraightEdge** [numixproject/numix-gtk-theme#260] opened 2015-10-19 11:21 UTC
I just upgraded to Ubuntu Wily and there are no check marks in the menus.
I tried with Nautilus, Gedit, and even the Network app in the traybar.
In Vivid all worked fine, GTK version is 3.16.7.

**Comment by khurshid-alam** [comment] 2015-10-20 13:23
Probably duplicate of #253

**Closed as completed** 2016-02-14 17:51 UTC
