### ISSUE TITLE
Numix doesn't show up in appearance under MATE

### ISSUE THREAD

**Issue by codeworkx** [numixproject/numix-gtk-theme#227] opened 2015-06-15 19:45 UTC
Numix can't be selected via appearance on MATE.
Adding "CursorTheme=default" to your index.theme makes it show up.

**Comment by satya164** [comment] 2015-08-06 21:29
Seems to be a bug with mate?

**Comment by jbicha** [comment] 2016-06-21 00:34
I believe this is a duplicate of issue #488

**Comment by lots0logs** [comment] 2016-06-21 00:36
I think you mean the other way around as this issue predates #488 :wink:  We'll continue this over on #488 anyway though!

**Closed as completed by lots0logs** 2016-06-21 00:36 UTC
