### ISSUE TITLE
nautilus 3.16 detailed view and sidepanel handle

### ISSUE THREAD

**Issue by lucazade** [numixproject/numix-gtk-theme#200] opened 2015-03-29 06:39 UTC
In the detailed view of Nautilus 3.16 the entries have a dotted line separator and a ugly sidepanel handle
![nautilus](https://cloud.githubusercontent.com/assets/1557010/6884364/18ef7180-d5ef-11e4-8a22-350cbbf39ca7.png)

**Comment by c4software** [comment] 2015-05-03 20:12
Anyone have an idea to solve this issue ?

**Comment by simonwjackson** [comment] 2015-05-03 21:35
+1 this issue

**Comment by macramole** [comment] 2015-05-18 15:08
+1 would like to remove dotted line

**Comment by khurshid-alam** [comment] 2015-05-18 17:04
This is probably by design and not a bug. However I do agree that older iteration was better.

**Comment by barracks510** [comment] 2015-06-11 05:10
+1 would like to remove. It's not specific to nautilus. E.G. gedit quick-open suffers the same dotted lines.

**Comment by satya164** [comment] 2015-06-11 14:23
Please use the `sass` branch with 3.16. Master doesn't have 3.16 support.

**Comment by crapp** [comment] 2015-06-11 22:21
@satya164 You should add this information to the Readme.

**Comment by satya164** [comment] 2015-06-11 22:51
It's a development branch.

**Comment by barracks510** [comment] 2015-06-12 23:17
On Sass Branch, the ugly side panel handle is gone, but the dotted/dashed lines between files in nautilus is still there.

**Comment by khurshid-alam** [comment] 2016-02-06 07:09
Fixed. Closing.

**Closed as completed by khurshid-alam** 2016-02-06 07:09 UTC
